spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  autoconfigure:
    exclude: net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration,net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer