server.port: 23457
spring:
  datasource.url: jdbc:postgresql://localhost:5432/chilldrill?user=chilldrill&password=chilldrill
  kafka.producer.bootstrap-servers: localhost:19092

jwt.secret: localsecretlocalsecretlocalsecre