server.port: 23457
spring:
  datasource.url: jdbc:postgresql://localhost:5432/chilldrill?user=chilldrill&password=chilldrill
  kafka.producer.bootstrap-servers: localhost:9092
  data.redis.url: redis://localhost:6379

jwt.secret: localsecretlocalsecretlocalsecre