spring:
  datasource.url: jdbc:postgresql://localhost:5432/chilldrill?user=chilldrill&password=chilldrill #TODO remove
  kafka.bootstrap-servers: localhost:9092
  kafka.consumer.bootstrap-servers: localhost:9092

grpc.client.chat.address: static://localhost:13457