name: Deploy auth

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  deploy-auth-backend:
    uses: ./.github/workflows/backend.yml
    with:
      app-name: auth
    secrets: inherit
