on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/frontend:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/frontend:latest
    