on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-chat-backend:
    uses: ./.github/workflows/build-backend.yml
    with:
      app-name: chat
    secrets: inherit
