name: Deploy Chat

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  deploy-chat:
    uses: ./.github/workflows/backend.yml
    with:
      app-name: chat
    secrets: inherit
