name: Deploy Chat

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  deploy:
    uses: ./.github/workflows/backend.yml
    with:
      app-name: chat
    secrets: inherit
    defaults:
      run:
        working-directory: ./backend
