name: Deploy Chat

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  deploy:
    uses: .github/workflows/backend.yml@master
    with:
      app-name: chat
    secrets: inherit
