on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy-codenames-backend:
    uses: ./.github/workflows/backend.yml
    with:
      app-name: codenames
    secrets: inherit
