on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-codenames-backend:
    uses: ./.github/workflows/build-backend.yml
    with:
      app-name: codenames
    secrets: inherit
