on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  deploy-events-backend:
    uses: ./.github/workflows/backend.yml
    with:
      app-name: events
    secrets: inherit
